### ISSUE TITLE
NobeokaとKagoshimaのタイルをいただけないでしょうか。

### ISSUE THREAD

**Issue by kenzkenz** [code4nara/jcp_maps#1]
## お世話になっております。私はOHTSUKA様が作られている米軍地図の地図タイルを活用させてもらっておるものです。まことにありがとうございます。さて、もしよろしければNobeokaとKagoshimaのタイルの作成をお願いできないでしょうか。お忙しいところ恐れ入りますが何卒よろしくお願いいたします。

なんとか自分で作成することができました。お騒がせしました。

**Comment by kochizufan** [comment]
対応遅くなってすみません、既に解決されたとの事でしたので、取り掛かりが遅くなりました。
さて、解決された件、
[こちら](https://github.com/code4nara/jcp_maps/wiki/%E6%8A%95%E5%BD%B1%E5%A4%89%E6%8F%9B%E3%81%AE%E5%86%85%E5%AE%B9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)での手順紹介に従って、対応点を調査されてgdalコマンドで処理されたのでしょうか。

もしそうであれば、その対応点データを共有いただくことは可能でしょうか。
それがあれば、こちらでもそれを元に作業して、他の人でも使えるようにすることができます。

オープンソース、オープンデータの活動は、一方向の提供だけではなく、そのようにみなで育てていくものですので、ぜひご提供いただけると大変助かります。
どうぞよろしくお願いいたします。

**Comment by kenzkenz** [comment]
OHTSUKA 様

ありがとうございます。落合です。
申し訳ありません。手順に従ってパイソンの準備等いろいろやってみたのですが、
私のパソコンのパイソンが３系だったため途中で挫折してしまいました。パイソン自体をほとんど私がわかっていないものですから。
そこで、結局のところQGISのジオリファレンサーを使ってしまいました。
そして、延岡と鹿児島と宮崎と東京の一部分をタイル化してみました。
もし良かったら見てみてください。
http://kenzkenz.xsrv.jp/m2/geo3.html
画面右の「背景」の下から９番目くらいにある「米軍統治直後」をクリックすると数十個の米軍地図が貼り付きます。
また、画面上部の「３D」をクリックするとcesiumに切り替わるので米軍地図が標高に沿って地面に貼り付きます。
実はこの３DもOHTSUKA様の公開されているページ（
http://qiita.com/kochizufan/items/b338ac856425c0fa925b）
を参考に実装しています。誠にありがとうございます。
その後、産総研さんと意見交換することがあって現在は産総研さん作成のプロバイダに変更しております。申し訳ありません。

私は宮崎県の職員で情報政策課に籍を置いております。
うちではGISやデータ利活用、オープンデータ、オープンソースに関する関心がほぼゼロだったので
現状を打破しようと思いWEBGISを作って庁内にちょこちょこ公開して職員の興味を喚起しているところです。
米軍地図タイルを見せると、かなり人の興味を引くことができるので凄く助かっております。今後ともよろしくお願いいたします。

もしも私にも何かを提供できるようならば是非お手伝いさせていただきたく思います。




2016年10月30日 11:40 OHTSUKA Ko-hei <notifications@github.com>:

**Comment by kenzkenz** [comment]
申し訳ありません。手順に従って準備等いろいろやってみたのですが、結局のところQGISのジオリファレンサーを使ってしまいました。

**Comment by kochizufan** [comment]
https://github.com/code4nara/jcp_maps/wiki/%E7%9A%86%E3%81%95%E3%82%93%E3%81%AE%E5%8A%A9%E3%81%91%E3%82%92%E3%81%8A%E5%80%9F%E3%82%8A%E3%81%97%E3%81%9F%E3%81%84%E4%BD%9C%E6%A5%AD

こちらにご協力いただくための手順などを新たにまとめました。
もしご興味持っていただけましたらどちらかでもご協力いただけると嬉しいです。

それでは、こちらのチケットはクローズしますね。
