### ISSUE TITLE
宮崎県延岡市のGCPポイントです。

### ISSUE THREAD

**Issue by kenzkenz** [code4nara/jcp_maps#2]
さっそく作ってみました。こんな感じで良かったでしょうか？拡張子をtxtに変えています。よろしくお願いいたします。

[txu-oclc-6542899.jpg.nobeoka.zb.points.txt](https://github.com/code4nara/jcp_maps/files/560444/txu-oclc-6542899.jpg.nobeoka.zb.points.txt)

**Comment by kochizufan** [comment]
ありがとうございます！
若干手直しが必要でした。
https://github.com/code4nara/jcp_maps/blob/master/pointsdata/txu-oclc-6542899.jpg.nobeoka.zb.points
手直し結果が上記のような感じで、
- X,Y座標が逆だった
- 桁数が間違っていた（地図座標罫線の値は1000000前後の値なので、場合により下3桁が省略されています。なのでたとえば663は663000の意味になります。省略されてない時もあります。一つ前のページには書いてあったのですが、作業お願いのページで明確に書いてなかったので、追加します。）

この点だけ修正すれば、おかげ様で延岡追加できました！
大変助かりました、ありがとうございます。
