### ISSUE TITLE
八代ののGCPポイントです

### ISSUE THREAD

**Issue by kenzkenz** [code4nara/jcp_maps#3]
いつもお世話になっております。八代のGCPポイントを作ってみました。間違いがありましたら申し訳ありません。よろしくお願い致しまます！
[txu-oclc-6551467.jpg.yatsushiro.zc.points.txt](https://github.com/code4nara/jcp_maps/files/2237714/txu-oclc-6551467.jpg.yatsushiro.zc.points.txt)

**Comment by kochizufan** [comment]
ありがとうございます。
最近触ってないので作業環境再起動するのが大変で、今少しだけ対応お待ちください。

**Comment by kenzkenz** [comment]
お世話になっております。落合です。
大塚さんにご迷惑かけるわけにはいきませんので全然無視してもらっていいです。
そうそう。話は変わりますがstroryを使おうとしている人がいたのでmaplatを推しました。
今後ともよろしくお願いいたします。



2018年8月2日(木) 15:13 OHTSUKA Ko-hei <notifications@github.com>:

**Comment by kochizufan** [comment]
いえ、協力を要請している以上迷惑などという事はなく大歓迎なのですが、いかんせん久しぶりすぎて...お恥ずかしい限りです。

Maplat推しの件、むちゃくちゃありがとうございます！ドキュメントとか不十分なので、わからないことがあれば私まで連絡いただければなんでもフォローしますとお伝えください。

**Comment by kenzkenz** [comment]
ご存知かもしれませんが、いま「ひなたGIS」に大塚さんが公開されている米軍地図タイルを大量に載せています。
背景→古地図フォルダ→戦後米軍地図フォルダ
です。ありがとうございます！


2018年8月3日(金) 10:42 OHTSUKA Ko-hei <notifications@github.com>:

**Comment by kochizufan** [comment]
すみません、大変遅くなりましたが対応しました。
やり方思い出しましたので以降は早く対応できると思います。
